# Generated by Django 4.2.4 on 2023-08-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
