# Generated by Django 4.2.4 on 2023-08-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='complete',
        ),
    ]
