# Generated by Django 4.2.4 on 2023-08-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_user_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
