# Generated by Django 4.2.4 on 2023-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_options_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
